-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.addresses
(
    id integer NOT NULL,
    customer_id integer NOT NULL,
    address_detail character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.balance_sheets
(
    id integer,
    customer_id integer,
    date date,
    price money
);

CREATE TABLE public.channels
(
    id integer NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.commercial_activities
(
    id integer NOT NULL,
    real_customer_id integer NOT NULL,
    starting_date date NOT NULL
);

CREATE TABLE public.corporate_customers
(
    customer_id integer NOT NULL,
    title character varying(50) NOT NULL,
    tax_no character varying(50) NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE public.customers
(
    id integer NOT NULL,
    customer_no character varying(10) NOT NULL,
    channel_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.real_customers
(
    customer_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE public.union_customer
(
    customer_id integer NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (customer_id)
);

ALTER TABLE public.addresses
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.balance_sheets
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.commercial_activities
    ADD FOREIGN KEY (real_customer_id)
    REFERENCES public.real_customers (customer_id)
    NOT VALID;


ALTER TABLE public.corporate_customers
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.customers
    ADD FOREIGN KEY (channel_id)
    REFERENCES public.channels (id)
    NOT VALID;


ALTER TABLE public.real_customers
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.union_customer
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (id)
    NOT VALID;

END;